version: '3.3'

services:

  front:
    container_name: bookstore_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/Bookstore'
      - '/Bookstore/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development